general {
    lock_cmd = pidof hyprlock || hyprlock       # avoid starting multiple hyprlock instances.
    before_sleep_cmd = loginctl lock-session    # lock before suspend.
    after_sleep_cmd = sleep 0.5s && hyprctl dispatch dpms on # to avoid having to press a key twice to turn on the display.
    inhibit_sleep = 3
}

listener {
    timeout = 600                               # 10 min
    # on-timeout = pidof hyprlock || 
    on-timeout = loginctl lock-session #&& sleep 1s && hyprctl dispatch dpms off
    on-resume = hyprctl dispatch dpms on
}

listener {
    timeout = 900                               # 15 min
    on-timeout = hyprlock --pre-suspend & systemctl suspend
}

